### PR TITLE
Add support for vector search and document level access control

### PR DESCRIPTION
**Pull request by sarah-widder**
- adds support for vector search when using Azure OpenAI on your data
- adds support for document level access control when using Azure OpenAI on your data via AAD Auth and the MS Graph API
- resolves endpoint/domain name issues

### CODE REVIEW

**Comment by avivansh** [comment]
@sarah-widder could you please share the resources for adding vector search capabilities.
Currently, https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions-extensions, in this documentation vector search isn't been included yet.

**Comment by sarah-widder** [comment]
Hi @avivansh we are still finalizing vector search support with associated documentation. We're targeting this in the next week, please stay tuned!

**Review by wernsingj — APPROVED** [review]

**Comment by phfontes** [comment]
Hello Sara!

We are trying to implement vector search and we have some doubts. Do I need to make any changes to the.env file? Adding values to the variables you entered in the app.py file, if so, I believe it is necessary to update the readme and .env file.

**Comment by hanhsia** [comment]
Hi Sarah,
when I send request with vector type information, it always returns 500 Internal server error. Here is my request:
https://<aoainame>.openai.azure.com/openai/deployments/gpt-4/extensions/chat/completions?api-version=2023-06-01-preview
curl -X 'POST' \
  'https://<name>.openai.azure.com/openai/deployments/gpt-4/extensions/chat/completions?api-version=2023-06-01-preview' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{"dataSources":[{"type":"AzureCognitiveSearch","parameters":{"endpoint":"https://<searchname>.search.windows.net","key":"<key>","indexName":"kbindex","semanticConfiguration":"","queryType":"vector","fieldsMapping":{"contentFieldsSeparator":"\n","contentFields":["content"],"filepathField":"file_name","titleField":null,"urlField":null,"vectorFields":["contentVector"]},"inScope":true,
"embeddingEndpoint":"https://<aoainame>.openai.azure.com/","embeddingKey":"<key>","roleInformation":"You are an AI assistant that helps people find information.","filter":"role/any(g:search.in(g, '\''1'\''))"}}],"messages":[{"role":"user","content":"how to clean c: root?"}],"deployment":"gpt-4","temperature":0,"top_p":1,"max_tokens":800,"stop":null,"stream":false}'
if the queryTYpe is "simple", it works well. I also called azure search api to retrieve dat using vectors. It also works. 
Is there anything missed in my request?
Thanks!

**Comment by sarah-widder** [comment]
Hi @avivansh , @phfontes , @hanhsia please see the updated documentation with vector search: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions-extensions 
Accepted queryType values are `vector`, `vectorSimpleHybrid`, `vectorSemanticHybrid`. For the `embeddingEndpoint` you need the full embeddings endpoint, e.g. `"https://{AOAI resource name}.openai.azure.com/openai/deployments/{Ada deployment name}/embeddings?api-version=2023-03-15-preview"`. Hope that helps :)

**Pull request merged**
