### PR TITLE
Allow UI configuration via environment variables

### LINKED ISSUE #277: Building a custom portal
I am interested in developing a personalized website using this repository as a foundation. I have cloned the repo and established a new container without modifying its contents. Subsequently, I specified the new container in the deployment.json file. However, upon deployment, the web application does not function as expected. Could you please advise on any potential oversights or provide a comprehensive guide for this process? My primary objective is to alter the website's branding.
Thanks

### LINKED ISSUE #522: [Feature Request] Enable configuration settings to control branding.
It would be great to have the logo and title / header added to configuration settings so we could just plug in our own logo URL and title.  This app is a great starter for organizations with limited developer resources, but forking and rebuilding/redeploying can be a challenge.

### LINKED ISSUE #553: Logo and Branding - The app is showing Contoso logo and Branding instead of Azure
contoso

### LINKED ISSUE #558: Rebrand sample app using TruBridge branding
{
TruBridge

### PR DESCRIPTION
**Pull request by iMicknl**
Many customers like this accelerator / sample because it is easy to set up and very clean. However, many customers struggle with making small branding changes. Especially since the sample has been rebranded to use Contoso + logo's, the demand for branding has risen.

This pull request primarily introduces branding customization to the application. The changes allow users to customize the title, logo, chat title, and chat description by setting environment variables. The most significant changes include the addition of new environment variables in the `.env.sample` file, the modification of the `app.py` file to use these variables, and the adjustment of frontend components to use these new settings.

**Related discussions:** #269, #438, #498, 
Fixes #522
Fixes #553
Fixes #558 
Fixes #277.

### Preview:

Example configuration:
```
UI_TITLE = "MicrosoftGPT"
UI_CHAT_TITLE = "Your safe and secure environment"
UI_CHAT_DESCRIPTION = "Start chatting with your own data now."
UI_LOGO = "https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg"
```

Screenshot:
image

### Changes
The changes allow users to modify the title, logo, and descriptions of the chat application via environment variables. These changes affect the `.env.sample`, `README.md`, `app.py`, `frontend/index.html`, `frontend/src/api/models.ts`, `frontend/src/pages/chat/Chat.module.css`, `frontend/src/pages/chat/Chat.tsx`, `frontend/src/pages/layout/Layout.module.css`, and `frontend/src/pages/layout/Layout.tsx` files.

UI Customization:

* [`.env.sample`](diffhunk://#diff-088d9f35d23a4347d221d71dd49b02b95001dff4abe637a40fe0bc04d502049cR18-R23): Added environment variables for UI customization including `UI_TITLE`, `UI_LOGO`, `UI_CHAT_LOGO`, `UI_CHAT_TITLE`, and `UI_CHAT_DESCRIPTION`.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L127-R137): Updated the documentation to reflect the new environment variables for UI customization and removed the section about updating the logo and headers in the `Chat.tsx` file. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L127-R137) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L148-L163) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L226-R223)
* [`app.py`](diffhunk://#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R15): Imported the `render_template` function and added new variables for the UI configuration. The `index` function now uses `render_template` to render the `index.html` file with the title. The `assets` function includes the UI configuration in the `frontend_settings`. [[1]](diffhunk://#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R15) [[2]](diffhunk://#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959L24-R32) [[3]](diffhunk://#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959L34-R42) [[4]](diffhunk://#diff-568470d013cd12e4f388206520da39ab9a4e4c3c6b95846cbc281abc1ba3c959R173-R179)
* [`frontend/index.html`](diffhunk://#diff-959f9cada636604db33bc1ba82fed347457dcb032c37ac195b4343c5f0ea6e72L7-R7): Updated the title to use the `title` variable.
* [`frontend/src/api/models.ts`](diffhunk://#diff-282efeb57d17756f9635c393e8bb9743b19d9e85ec6c2915d59b46394a7a3c3aR104-R115): Added a new `UI` type and updated the `FrontendSettings` type to include the `ui` property.
* [`frontend/src/pages/chat/Chat.module.css`](diffhunk://#diff-1d93f5296964ba277a6baa09040e550b67bee97ca3a518077f0b8b2996a6a25fL65-R65): Updated the `chatIcon` class to have an auto width.
* [`frontend/src/pages/chat/Chat.tsx`](diffhunk://#diff-acfbdb512c79eb9c53d0c2488f520793646422af0dac0a8c83b6c5080ffe784aR46): Updated the chat page to use the UI configuration from the frontend settings. The chat logo, title, and description are now customizable. [[1]](diffhunk://#diff-acfbdb512c79eb9c53d0c2488f520793646422af0dac0a8c83b6c5080ffe784aR46) [[2]](diffhunk://#diff-acfbdb512c79eb9c53d0c2488f520793646422af0dac0a8c83b6c5080ffe784aL627-R633)
* [`frontend/src/pages/layout/Layout.module.css`](diffhunk://#diff-02d336b6f349f34292f48f005801c292b00e794af42bbef9207341f11964b889L36-R36): Updated the `headerIcon` class to have an auto width.
* [`frontend/src/pages/layout/Layout.tsx`](diffhunk://#diff-a930475a94067349f398d3eeab82c557cfda92df5b3870b3699bbec04a5035c5R16): Updated the layout to use the UI configuration from the frontend settings. The logo and title in the header are now customizable. [[1]](diffhunk://#diff-a930475a94067349f398d3eeab82c557cfda92df5b3870b3699bbec04a5035c5R16) [[2]](diffhunk://#diff-a930475a94067349f398d3eeab82c557cfda92df5b3870b3699bbec04a5035c5L50-R56)

### CODE REVIEW

**Comment by sarah-widder** [comment]
Hi @iMicknl , thank you for this delightfully thorough and well-documented PR! I'm just getting ready to merge #460 which would require adjusting this to use the async render_template function from Quart. Do you see any additional issues with migrating this over to Quart?

**Comment by iMicknl** [comment]
@sarah-widder haven't tried it yet with Quart, but will rebase on main when #460 is merged and adapt to the new changes. Shouldn't be too difficult!

Would you agree with the current proposal in this PR? I was hesitating to add a JSON based format, which can contain more branding options easily, but this might be too difficult for starting users. The current proposal is only to allow a few small changes. Customers can still change the code for more changes.

**Comment by iMicknl** [comment]
Rebased on main! My latest thought is that `branding` is maybe not the right prefix, especially if there will be additions in the future like `HIDE_SHARE_BUTTON`.

Perhaps we should prefix it with `UI` or `INTERFACE`? What do you think.

```
UI_TITLE = "MicrosoftGPT"
UI_CHAT_TITLE = "Your safe and secure environment"
UI_CHAT_DESCRIPTION = "Start chatting with your own data now."
UI_LOGO = "https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg"
```

**Comment by sarah-widder** [comment]
@iMicknl that's a great point - let's use `UI_*` instead of `BRANDING_`. Maybe adjust the frontend settings section to something like `ui_constants` as well?

**Comment by iMicknl** [comment]
Rebased on `main` and changed the naming to UI. Regarding `frontend_settings`, for now I think this would sufficient since there are more settings here that will be sent to the front-end.

**Comment by RylandDeGregory** [comment]
I love the idea of this PR, and think the proposed implementation is both clean and user-friendly. However, I would like to see 1 more setting be added in order to set the favicon to a user-defined image.

**Review by federel — APPROVED** [review]

**Comment by iMicknl** [comment]
Done + rebased on main.

**Review by sarah-widder — APPROVED** [review]
Really nice work, thanks @iMicknl !

**Comment by mdsa3d** [comment]
I think there is bug in favicon icon implementation, it doesnt update in the browser tab.

**Pull request merged**
