### PR TITLE
Add JSON validation and parser to data_utils.py

### PR DESCRIPTION
**Pull request by HARISHKUMAR1112001**
This pull request addresses an issue in the data_utils.py file by introducing validation and parsing functionality for JSON files. Currently, the file lacks proper validation and parsing mechanisms for JSON, which can lead to potential errors or unexpected behavior when working with JSON data.

To resolve this, the following changes have been made:

1. **Added a JSON extension in FILE_FORMAT_DICT:** This allows the creation of index using JSON documents.

2. **A new class, JSONParser, has been introduced to handle the parsing of JSON files :** This class provides methods to read and parse JSON data from a file, returning the parsed data as a Python object. The parser handles common scenarios, such as parsing nested objects and arrays, and supports various data types present in JSON.

By incorporating these changes, the data_utils.py file gains the ability to validate JSON files and parse their contents reliably. This enhancement enhances the overall robustness and compatibility of the codebase when dealing with JSON data.

The modifications have been thoroughly tested to ensure proper functionality. Any feedback or suggestions for further improvements are welcome.

Please review this pull request and consider merging it into the main branch.

### CODE REVIEW

**Review by Harish-Tricon — APPROVED** [review]

**Comment by Harish-Tricon** [comment]
@microsoft-github-policy-service agree

**Comment by Harish-Tricon** [comment]
> @microsoft-github-policy-service agree

**Comment by HARISHKUMAR1112001** [comment]
@microsoft-github-policy-service agree

**Comment by HARISHKUMAR1112001** [comment]
> @HARISHKUMAR1112001 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by Harish-Tricon — APPROVED** [review]

**Comment by sarah-widder** [comment]
Hi @HARISHKUMAR1112001 thanks for your contribution. At this time we do not intend to support JSON files with the data preparation script, as the resulting index is intended to be used with Azure OpenAI on your data: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/use-your-data which does not directly support JSON files. I will close the PR for now.

**Pull request closed without merging**
