### PR TITLE
Add feedback buttons with optional setting

### PR DESCRIPTION
**Pull request by sarah-widder**
Adds feedback buttons to the bot answers to allow user feedback to be logged to the CosmosDB when chat history is enabled.

Liked state:
image (1)

On clicking thumbs down:
image (2)

On clicking "report inappropriate content"
image (3)

### CODE REVIEW

**Comment by QuentinAd** [comment]
This will be very useful for gathering feedback from our users and pinpointing where bugs or unexpected/undesired behaviors may have raised. Thank you!

Looks like we will be able to easily get back to the chat history for a certain conversation in cosmosDB and trace when feedback was submitted so that we may associate a user, a conversation and even a message with a feedback.

**Comment by piquet-h** [comment]
What is needed to get this merged?

**Review by sarah-widder — COMMENTED** [review]
Looks great, thanks for getting it across the finish line Ian!

**Review by wernsingj — APPROVED** [review]

**Comment by jainrahulsethi** [comment]
@sarah-widder: 
Thanks for the amazing work!
Is it possible to also have a text field, where in the user can add a custom text to the feedback?

**Pull request merged**
