### PR TITLE
Changed index

### PR DESCRIPTION
**Pull request by fbanespo1**

### CODE REVIEW

**Review by fbanespo1 — COMMENTED** [review]
Good

**Comment by fbanespo1** [comment]
All good

**Review by fbanespo1 — COMMENTED** [review]
good

**Review by fbanespo1 — COMMENTED** [review]
approved

**Comment by fbanespo1** [comment]
@microsoft-github-policy-service agree

**Comment by pamelafox** [comment]
This looks like an accidental PR, since the change is not a globally useful change but one specific to your org. Closing this PR.

**Pull request closed without merging**
