### PR TITLE
Ignore Enter during IME conversion.

### PR DESCRIPTION
**Pull request by derbuihan**
## Summary

This pull request fixes a issue with the Input Method Editor (IME) being sent on Enter during conversion. This problem happens when typing Japanese, Chinese, Korean, and other languages that use IMEs.

## Changes

To fix this issue, we use the `isComposing` property of nativeEvent. The `isComposing` property is true while typing in IME, so we can ignore Enter during IME conversion.

### CODE REVIEW

**Review by piroyoung — APPROVED** [review]
LGTM

**Review by piroyoung — APPROVED** [review]
lgtm

**Comment by morihaya** [comment]
@sarah-widder ,

I was wondering if you could take a moment to review and possibly merge this PR. For those of us in the kanji-using communities, like Japanese and Chinese speakers, this change is pivotal and would significantly enhance our application experience.

Looking forward to your feedback.
Best,

**Comment by morihaya** [comment]
Thanks!

**Pull request closed without merging**
